// Seed data for the Google Workspace mock (Sheets + Slides).
// Shape mirrors fields read by the official workspace MCP tools.
// Imported by lib/db.mjs to populate SQLite on first run.

const COLS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

function makeCell(value) {
  if (value && typeof value === 'object' && 'value' in value) return value;
  return typeof value === 'number' ? { value, type: 'number' } : { value };
}

function tableCells(startRow, rows) {
  const cells = {};
  rows.forEach((row, idx) => {
    row.forEach((value, colIdx) => {
      cells[`${COLS[colIdx]}${startRow + idx}`] = makeCell(value);
    });
  });
  return cells;
}

function quoteCells(startRow, rows) {
  const cells = {};
  rows.forEach(([sku, product, a, b, c, recommended], idx) => {
    const row = startRow + idx;
    const best = Math.min(a, b, c);
    const spread = Math.round(((Math.max(a, b, c) - best) / best) * 1000) / 1000;
    Object.assign(cells, tableCells(row, [[sku, product, a, b, c, best, spread, recommended]]));
    cells[`F${row}`].formula = `=MIN(C${row}:E${row})`;
    cells[`G${row}`].formula = `=(MAX(C${row}:E${row})-MIN(C${row}:E${row}))/MIN(C${row}:E${row})`;
  });
  return cells;
}

function inventoryCells(startRow, rows) {
  return tableCells(startRow, rows.map(([sku, product, warehouse, onHand, inTransit, safety, stockoutDays, lastReplenish, supplier, unitCost, status]) => [
    sku, product, warehouse, onHand, inTransit, safety, stockoutDays, lastReplenish, supplier, unitCost,
    Math.round(onHand * unitCost * 100) / 100, status,
  ]));
}

export function buildSeed() {
  return {
    spreadsheets: {
      'sheet-q3-budget-001': {
        spreadsheetId: 'sheet-q3-budget-001',
        properties: {
          title: 'Q3 Marketing Budget',
          locale: 'en_US',
          timeZone: 'America/Los_Angeles',
        },
        sheets: [
          {
            properties: {
              sheetId: 0,
              title: 'Summary',
              index: 0,
              gridProperties: { rowCount: 100, columnCount: 26 },
            },
            cells: {
              A1: { value: 'Channel' },
              B1: { value: 'Planned' },
              C1: { value: 'Actual' },
              D1: { value: 'Variance', formula: '=C{row}-B{row}' },
              A2: { value: 'Search Ads' },
              B2: { value: 12000, type: 'number' },
              C2: { value: 11280, type: 'number' },
              D2: { value: -720, type: 'number', formula: '=C2-B2' },
              A3: { value: 'Display' },
              B3: { value: 8000, type: 'number' },
              C3: { value: 9120, type: 'number' },
              D3: { value: 1120, type: 'number', formula: '=C3-B3' },
              A4: { value: 'Influencer' },
              B4: { value: 15000, type: 'number' },
              C4: { value: 14400, type: 'number' },
              D4: { value: -600, type: 'number', formula: '=C4-B4' },
              A5: { value: 'Events' },
              B5: { value: 22000, type: 'number' },
              C5: { value: 21750, type: 'number' },
              D5: { value: -250, type: 'number', formula: '=C5-B5' },
              A6: { value: 'Total', bold: true },
              B6: { value: 57000, type: 'number', formula: '=SUM(B2:B5)' },
              C6: { value: 56550, type: 'number', formula: '=SUM(C2:C5)' },
              D6: { value: -450, type: 'number', formula: '=C6-B6' },
            },
          },
          {
            properties: {
              sheetId: 1,
              title: 'Spend by Week',
              index: 1,
              gridProperties: { rowCount: 100, columnCount: 26 },
            },
            cells: {
              A1: { value: 'Week' },
              B1: { value: 'Search' },
              C1: { value: 'Display' },
              D1: { value: 'Influencer' },
              E1: { value: 'Events' },
              A2: { value: 'W27' }, B2: { value: 2820, type: 'number' }, C2: { value: 2280, type: 'number' }, D2: { value: 3600, type: 'number' }, E2: { value: 5440, type: 'number' },
              A3: { value: 'W28' }, B3: { value: 2810, type: 'number' }, C3: { value: 2280, type: 'number' }, D3: { value: 3600, type: 'number' }, E3: { value: 5430, type: 'number' },
              A4: { value: 'W29' }, B4: { value: 2825, type: 'number' }, C4: { value: 2280, type: 'number' }, D4: { value: 3600, type: 'number' }, E4: { value: 5440, type: 'number' },
              A5: { value: 'W30' }, B5: { value: 2825, type: 'number' }, C5: { value: 2280, type: 'number' }, D5: { value: 3600, type: 'number' }, E5: { value: 5440, type: 'number' },
            },
          },
          {
            properties: {
              sheetId: 2,
              title: 'Notes',
              index: 2,
              gridProperties: { rowCount: 50, columnCount: 10 },
            },
            cells: {
              A1: { value: 'Owner' },
              B1: { value: 'Note' },
              A2: { value: 'priya@' },
              B2: { value: 'Display overspend driven by reallocated banner test, see ticket MKT-318.' },
              A3: { value: 'lee@' },
              B3: { value: 'Influencer renewal pushed to Q4; reconcile with finance.' },
            },
          },
        ],
      },
      'sheet-roadmap-002': {
        spreadsheetId: 'sheet-roadmap-002',
        properties: {
          title: '2026 Product Roadmap',
          locale: 'en_US',
          timeZone: 'America/Los_Angeles',
        },
        sheets: [
          {
            properties: {
              sheetId: 0,
              title: 'Roadmap',
              index: 0,
              gridProperties: { rowCount: 100, columnCount: 26 },
            },
            cells: {
              A1: { value: 'Initiative' },
              B1: { value: 'Owner' },
              C1: { value: 'Status' },
              D1: { value: 'Target' },
              A2: { value: 'Self-serve onboarding v2' },
              B2: { value: 'Maya' },
              C2: { value: 'In progress' },
              D2: { value: 'Q1' },
              A3: { value: 'Billing migration' },
              B3: { value: 'Andre' },
              C3: { value: 'Planning' },
              D3: { value: 'Q2' },
              A4: { value: 'Workspace shared inbox' },
              B4: { value: 'Priya' },
              C4: { value: 'Discovery' },
              D4: { value: 'Q2' },
              A5: { value: 'Mobile redesign' },
              B5: { value: 'Lee' },
              C5: { value: 'Backlog' },
              D5: { value: 'Q3' },
            },
          },
        ],
      },

      // ── Supplier Evaluation Matrix (3 sheets, ~90 rows) ──
      'sheet-supplier-eval-003': {
        spreadsheetId: 'sheet-supplier-eval-003',
        properties: { title: 'Supplier Evaluation Matrix', locale: 'en_US', timeZone: 'Asia/Shanghai' },
        sheets: [
          {
            properties: { sheetId: 0, title: 'Supplier Overview', index: 0, gridProperties: { rowCount: 200, columnCount: 26 } },
            cells: {
              A1: { value: 'Supplier' }, B1: { value: 'Country' }, C1: { value: 'Category' },
              D1: { value: 'Contact' }, E1: { value: 'Certifications' }, F1: { value: 'MOQ' },
              G1: { value: 'Lead Time (days)' }, H1: { value: 'Payment Terms' }, I1: { value: 'Rating' }, J1: { value: 'Notes' },
              A2: { value: '深圳流明科技 (Shenzhen Lumen)' }, B2: { value: 'CN' }, C2: { value: 'LED Lighting' },
              D2: { value: 'Wei Zhang, wei@lumen.cn' }, E2: { value: 'ISO9001, BSCI' }, F2: { value: 500, type: 'number' },
              G2: { value: 35, type: 'number' }, H2: { value: 'Net 30' }, I2: { value: 4.2, type: 'number' }, J2: { value: 'Preferred supplier since 2024; passed on-site audit Q1' },
              A3: { value: '宁波港塑料 (Ningbo Harbor)' }, B3: { value: 'CN' }, C3: { value: 'Packaging' },
              D3: { value: 'Li Fang' }, E3: { value: 'ISO9001' }, F3: { value: 1000, type: 'number' },
              G3: { value: 28, type: 'number' }, H3: { value: 'Net 60' }, I3: { value: 3.8, type: 'number' }, J3: { value: 'High MOQ but competitive pricing' },
              A4: { value: '青岛绿野工具 (Qingdao Greenfield)' }, B4: { value: 'CN' }, C4: { value: 'Garden Tools' },
              D4: { value: 'Mei Chen, mei@greenfield.com' }, E4: { value: 'ISO9001, FSC' }, F4: { value: 300, type: 'number' },
              G4: { value: 42, type: 'number' }, H4: { value: 'Net 30' }, I4: { value: 4.5, type: 'number' }, J4: { value: '' },
              A5: { value: 'Istanbul Metalworks' }, B5: { value: 'TR' }, C5: { value: 'Kitchen Hardware' },
              D5: { value: 'Emre Yilmaz' }, E5: { value: 'CE, BSCI' }, F5: { value: 200, type: 'number' },
              G5: { value: 45, type: 'number' }, H5: { value: 'L/C at sight' }, I5: { value: 3.5, type: 'number' }, J5: { value: 'New supplier; trial order placed 2026-03' },
              A6: { value: 'Rajkot Precision Parts' }, B6: { value: 'IN' }, C6: { value: 'Automotive' },
              D6: { value: 'Anuj Patel, anuj@rajkotpp.in' }, E6: { value: 'ISO9001, IATF16949' }, F6: { value: 1000, type: 'number' },
              G6: { value: 55, type: 'number' }, H6: { value: 'Net 90' }, I6: { value: 4.0, type: 'number' }, J6: { value: 'Long lead time offset by 30% cost advantage' },
              A7: { value: '苏州明居制造 (Suzhou BrightHome)' }, B7: { value: 'CN' }, C7: { value: 'Home & Kitchen' },
              D7: { value: 'Iris Wang' }, E7: { value: 'ISO9001, BSCI, FDA' }, F7: { value: 200, type: 'number' },
              G7: { value: 30, type: 'number' }, H7: { value: 'Net 30' }, I7: { value: 4.7, type: 'number' }, J7: { value: 'Top performer; expanding capacity Q3' },
              A8: { value: 'São Paulo Têxtil' }, B8: { value: 'BR' }, C8: { value: 'Textiles' },
              D8: { value: 'Ana Costa' }, E8: { value: 'OEKO-TEX' }, F8: { value: 500, type: 'number' },
              G8: { value: 60, type: 'number' }, H8: { value: 'Net 45' }, I8: { value: 3.2, type: 'number' }, J8: { value: 'Quality inconsistency on dye lots; corrective action pending' },
              A9: { value: '东莞新星宠物 (Dongguan Nova Pet)' }, B9: { value: 'CN' }, C9: { value: 'Pet Supplies' },
              D9: { value: 'Owen Brooks' }, E9: { value: 'ISO9001' }, F9: { value: 300, type: 'number' },
              G9: { value: 25, type: 'number' }, H9: { value: 'T/T 30%+70%' }, I9: { value: 4.1, type: 'number' }, J9: { value: '' },
              A10: { value: 'Guadalajara Artesanías' }, B10: { value: 'MX' }, C10: { value: 'Home Décor' },
              D10: { value: 'Lina Gomez' }, E10: { value: '' }, F10: { value: 50, type: 'number' },
              G10: { value: 40, type: 'number' }, H10: { value: 'Net 30' }, I10: { value: 3.9, type: 'number' }, J10: { value: 'Artisan workshop; no formal certs but consistent quality' },
              A11: { value: '杭州维包贸易 (Hangzhou Wellpack)' }, B11: { value: 'CN' }, C11: { value: 'Packaging' },
              D11: { value: 'Jon Miller' }, E11: { value: 'ISO9001, FSC' }, F11: { value: 2000, type: 'number' },
              G11: { value: 20, type: 'number' }, H11: { value: 'Net 30' }, I11: { value: 4.3, type: 'number' }, J11: { value: 'Fastest lead time in category' },
              A12: { value: 'Ho Chi Minh Ceramics' }, B12: { value: 'VN' }, C12: { value: 'Home & Kitchen' },
              D12: { value: 'Tran Nguyen' }, E12: { value: 'ISO9001' }, F12: { value: 500, type: 'number' },
              G12: { value: 38, type: 'number' }, H12: { value: 'Net 45' }, I12: { value: 3.6, type: 'number' }, J12: { value: 'Breakage rate 4.2% last shipment — need to address' },
              A13: { value: '佛山北极星照明 (Foshan Northstar)' }, B13: { value: 'CN' }, C13: { value: 'LED Lighting' },
              D13: { value: 'Yuki Tanaka' }, E13: { value: 'ISO9001, UL' }, F13: { value: 1000, type: 'number' },
              G13: { value: 30, type: 'number' }, H13: { value: 'Net 60' }, I13: { value: 4.4, type: 'number' }, J13: { value: 'Secondary source for Lumen; competitive on high-volume' },
              A14: { value: 'Dhaka Leather Works' }, B14: { value: 'BD' }, C14: { value: 'Accessories' },
              D14: { value: 'Rahim Khan' }, E14: { value: 'BSCI' }, F14: { value: 200, type: 'number' },
              G14: { value: 50, type: 'number' }, H14: { value: 'L/C 60 days' }, I14: { value: 3.3, type: 'number' }, J14: { value: 'Price competitive but compliance docs often late' },
              A15: { value: '义乌经纬供应 (Yiwu Meridian)' }, B15: { value: 'CN' }, C15: { value: 'General Merchandise' },
              D15: { value: 'Ravi Patel' }, E15: { value: 'ISO9001' }, F15: { value: 100, type: 'number' },
              G15: { value: 15, type: 'number' }, H15: { value: 'Net 15' }, I15: { value: 3.7, type: 'number' }, J15: { value: 'Small orders, fast turnaround; quality varies by product line' },
              A16: { value: 'Izmir Glass' }, B16: { value: 'TR' }, C16: { value: 'Home Décor' },
              D16: { value: 'Ayşe Kaya' }, E16: { value: 'CE' }, F16: { value: 300, type: 'number' },
              G16: { value: 48, type: 'number' }, H16: { value: 'Net 60' }, I16: { value: 4.0, type: 'number' }, J16: { value: 'Handblown glass; high margins, fragile shipping' },
              A17: { value: '厦门蓝波户外 (Xiamen Bluewave)' }, B17: { value: 'CN' }, C17: { value: 'Outdoor' },
              D17: { value: 'Lee Wu' }, E17: { value: 'ISO9001, BSCI' }, F17: { value: 500, type: 'number' },
              G17: { value: 32, type: 'number' }, H17: { value: 'Net 30' }, I17: { value: 4.6, type: 'number' }, J17: { value: 'Camping + hiking gear; strong Amazon seller reviews' },
              A18: { value: 'Chennai Spice Exports' }, B18: { value: 'IN' }, C18: { value: 'Food & Beverage' },
              D18: { value: 'Priya Nair' }, E18: { value: 'FSSAI, ISO22000' }, F18: { value: 100, type: 'number' },
              G18: { value: 45, type: 'number' }, H18: { value: 'Net 30' }, I18: { value: 4.1, type: 'number' }, J18: { value: 'Organic turmeric + pepper; USDA organic pending' },
              A19: { value: '广州兰花美容 (Guangzhou Orchid Beauty)' }, B19: { value: 'CN' }, C19: { value: 'Beauty' },
              D19: { value: 'Sara Li, sara@orchid-beauty.cn' }, E19: { value: 'ISO22716, FDA, NMPA' }, F19: { value: 3000, type: 'number' },
              G19: { value: 35, type: 'number' }, H19: { value: 'Net 60' }, I19: { value: 4.8, type: 'number' }, J19: { value: 'OEM/ODM beauty; highest rated; minimum 3k MOQ is a constraint' },
              A20: { value: 'Monterrey Steel' }, B20: { value: 'MX' }, C20: { value: 'Industrial' },
              D20: { value: 'Carlos Ruiz' }, E20: { value: 'ISO9001, ASTM' }, F20: { value: 5000, type: 'number' },
              G20: { value: 22, type: 'number' }, H20: { value: 'Net 30' }, I20: { value: 4.2, type: 'number' }, J20: { value: 'USMCA nearshoring option; competitive vs CN on landed cost' },
              ...tableCells(21, [
                ['Pacific Northwest Tools', 'US', 'Garden Tools', 'Erin Marsh', 'ISO9001', 250, 24, 'Net 30', 4.1, 'Nearshore pruning accessory backup; tariff-sensitive quotes'],
                ['Osaka Home Goods', 'JP', 'Home & Kitchen', 'Kenji Sato', 'JIS, ISO9001', 300, 37, 'Net 45', 4.2, 'Premium finish, small capacity window in July'],
                ['Busan Alloy Works', 'KR', 'Kitchen Hardware', 'Min Park', 'ISO9001, CE', 400, 34, 'Net 30', 3.9, 'Strong stainless line, higher tooling charge'],
                ['Poznan Packaging', 'PL', 'Packaging', 'Kasia Nowak', 'FSC, ISO14001', 1500, 29, 'Net 45', 4.0, 'EU backup for kraft mailers'],
                ['Bandung Outdoor Supply', 'ID', 'Outdoor', 'Raka Putra', 'BSCI', 600, 49, 'T/T 30%+70%', 3.4, 'Competitive tent poles but late sample reports'],
                ['Bangkok Wellness Labs', 'TH', 'Beauty', 'Nok Chai', 'ISO22716, FDA', 2000, 33, 'Net 45', 4.3, 'Secondary serum filler for promo surge'],
                ['Penang Pet Comfort', 'MY', 'Pet Supplies', 'Aina Rahman', 'ISO9001, BSCI', 350, 27, 'Net 30', 4.0, 'Air-freight capable bed insert supplier'],
                ['Porto Cork & Home', 'PT', 'Home Décor', 'Ines Silva', 'CE, FSC', 200, 41, 'Net 45', 3.8, 'Cork decor line; fragile but high margin'],
                ['Lombardy Fixture Co.', 'IT', 'Industrial', 'Marco Rizzi', 'CE, ISO9001', 700, 46, 'Net 60', 4.1, 'EU shelving option, quote expires June 30'],
                ['Valencia Glass Studio', 'ES', 'Home Décor', 'Lucia Ortega', 'CE', 180, 44, 'Net 45', 3.7, 'Handblown glass, limited kiln capacity'],
                ['Toronto Pet Goods', 'CA', 'Pet Supplies', 'Nora Singh', 'ISO9001', 500, 21, 'Net 30', 4.2, 'Backup dog-bed stitching line'],
                ['Rayong LED Components', 'TH', 'LED Lighting', 'Somchai Prasert', 'ISO9001, UL', 800, 31, 'Net 45', 4.1, 'Panel driver supplier; UL file pending update'],
                ['Krakow Auto Filters', 'PL', 'Automotive', 'Marek Zielinski', 'IATF16949', 1200, 35, 'Net 60', 3.9, 'Oil filter dual-source candidate'],
                ['Da Nang Ceramic Finishers', 'VN', 'Home & Kitchen', 'Mai Pham', 'ISO9001', 450, 36, 'Net 45', 3.5, 'Can rework vase glazing but needs QC sign-off'],
              ]),
            },
          },
          {
            properties: { sheetId: 1, title: 'Quote Comparison', index: 1, gridProperties: { rowCount: 200, columnCount: 26 } },
            cells: {
              A1: { value: 'SKU' }, B1: { value: 'Product' }, C1: { value: 'Supplier A (USD)' },
              D1: { value: 'Supplier B (USD)' }, E1: { value: 'Supplier C (USD)' },
              F1: { value: 'Best Price' }, G1: { value: 'Spread %' }, H1: { value: 'Recommended' },
              A2: { value: 'LED-PANEL-60W' }, B2: { value: '60W LED Panel Light' },
              C2: { value: 12.50, type: 'number' }, D2: { value: 14.20, type: 'number' }, E2: { value: 13.80, type: 'number' },
              F2: { value: 12.50, type: 'number', formula: '=MIN(C2:E2)' }, G2: { value: 0.136, type: 'number', formula: '=(MAX(C2:E2)-MIN(C2:E2))/MIN(C2:E2)' }, H2: { value: 'Supplier A' },
              A3: { value: 'PKG-KRAFT-M' }, B3: { value: 'Kraft Mailer Box (Medium)' },
              C3: { value: 0.42, type: 'number' }, D3: { value: 0.38, type: 'number' }, E3: { value: 0.45, type: 'number' },
              F3: { value: 0.38, type: 'number', formula: '=MIN(C3:E3)' }, G3: { value: 0.184, type: 'number', formula: '=(MAX(C3:E3)-MIN(C3:E3))/MIN(C3:E3)' }, H3: { value: 'Supplier B' },
              A4: { value: 'TOOL-PRUNE-01' }, B4: { value: 'Bypass Pruning Shears' },
              C4: { value: 3.20, type: 'number' }, D4: { value: 3.85, type: 'number' }, E4: { value: 2.95, type: 'number' },
              F4: { value: 2.95, type: 'number', formula: '=MIN(C4:E4)' }, G4: { value: 0.305, type: 'number', formula: '=(MAX(C4:E4)-MIN(C4:E4))/MIN(C4:E4)' }, H4: { value: 'Supplier C' },
              A5: { value: 'KIT-KNIFE-5PC' }, B5: { value: '5-Piece Kitchen Knife Set' },
              C5: { value: 18.00, type: 'number' }, D5: { value: 16.50, type: 'number' }, E5: { value: 17.20, type: 'number' },
              F5: { value: 16.50, type: 'number', formula: '=MIN(C5:E5)' }, G5: { value: 0.091, type: 'number', formula: '=(MAX(C5:E5)-MIN(C5:E5))/MIN(C5:E5)' }, H5: { value: 'Supplier B' },
              A6: { value: 'PET-BED-LG' }, B6: { value: 'Orthopedic Dog Bed (Large)' },
              C6: { value: 9.80, type: 'number' }, D6: { value: 11.20, type: 'number' }, E6: { value: 10.50, type: 'number' },
              F6: { value: 9.80, type: 'number', formula: '=MIN(C6:E6)' }, G6: { value: 0.143, type: 'number', formula: '=(MAX(C6:E6)-MIN(C6:E6))/MIN(C6:E6)' }, H6: { value: 'Supplier A' },
              A7: { value: 'DECOR-VASE-CER' }, B7: { value: 'Ceramic Flower Vase, 12"' },
              C7: { value: 4.60, type: 'number' }, D7: { value: 5.10, type: 'number' }, E7: { value: 4.30, type: 'number' },
              F7: { value: 4.30, type: 'number', formula: '=MIN(C7:E7)' }, G7: { value: 0.186, type: 'number', formula: '=(MAX(C7:E7)-MIN(C7:E7))/MIN(C7:E7)' }, H7: { value: 'Supplier C' },
              A8: { value: 'PKG-BUBBLE-LG' }, B8: { value: 'Bubble Wrap Roll (Large)' },
              C8: { value: 1.80, type: 'number' }, D8: { value: 1.65, type: 'number' }, E8: { value: 1.90, type: 'number' },
              F8: { value: 1.65, type: 'number', formula: '=MIN(C8:E8)' }, G8: { value: 0.152, type: 'number', formula: '=(MAX(C8:E8)-MIN(C8:E8))/MIN(C8:E8)' }, H8: { value: 'Supplier B' },
              A9: { value: 'CAMP-TENT-2P' }, B9: { value: '2-Person Camping Tent' },
              C9: { value: 22.00, type: 'number' }, D9: { value: 25.50, type: 'number' }, E9: { value: 23.80, type: 'number' },
              F9: { value: 22.00, type: 'number', formula: '=MIN(C9:E9)' }, G9: { value: 0.159, type: 'number', formula: '=(MAX(C9:E9)-MIN(C9:E9))/MIN(C9:E9)' }, H9: { value: 'Supplier A' },
              A10: { value: 'BEAUTY-SERUM-VC' }, B10: { value: 'Vitamin C Serum 30ml' },
              C10: { value: 1.20, type: 'number' }, D10: { value: 1.45, type: 'number' }, E10: { value: 1.35, type: 'number' },
              F10: { value: 1.20, type: 'number', formula: '=MIN(C10:E10)' }, G10: { value: 0.208, type: 'number', formula: '=(MAX(C10:E10)-MIN(C10:E10))/MIN(C10:E10)' }, H10: { value: 'Supplier A' },
              A11: { value: 'AUTO-FILTER-OIL' }, B11: { value: 'Oil Filter (Universal)' },
              C11: { value: 0.95, type: 'number' }, D11: { value: 0.88, type: 'number' }, E11: { value: 1.10, type: 'number' },
              F11: { value: 0.88, type: 'number', formula: '=MIN(C11:E11)' }, G11: { value: 0.25, type: 'number', formula: '=(MAX(C11:E11)-MIN(C11:E11))/MIN(C11:E11)' }, H11: { value: 'Supplier B' },
              A12: { value: 'SPICE-TURM-ORG' }, B12: { value: 'Organic Turmeric Powder 500g' },
              C12: { value: 3.40, type: 'number' }, D12: { value: 3.80, type: 'number' }, E12: { value: 3.60, type: 'number' },
              F12: { value: 3.40, type: 'number', formula: '=MIN(C12:E12)' }, G12: { value: 0.118, type: 'number', formula: '=(MAX(C12:E12)-MIN(C12:E12))/MIN(C12:E12)' }, H12: { value: 'Supplier A' },
              A13: { value: 'STEEL-SHELF-3T' }, B13: { value: '3-Tier Steel Storage Shelf' },
              C13: { value: 14.00, type: 'number' }, D13: { value: 12.80, type: 'number' }, E13: { value: 15.50, type: 'number' },
              F13: { value: 12.80, type: 'number', formula: '=MIN(C13:E13)' }, G13: { value: 0.211, type: 'number', formula: '=(MAX(C13:E13)-MIN(C13:E13))/MIN(C13:E13)' }, H13: { value: 'Supplier B' },
              A14: { value: 'LEATHER-WALLET' }, B14: { value: 'Genuine Leather Bifold Wallet' },
              C14: { value: 5.50, type: 'number' }, D14: { value: 4.80, type: 'number' }, E14: { value: 6.20, type: 'number' },
              F14: { value: 4.80, type: 'number', formula: '=MIN(C14:E14)' }, G14: { value: 0.292, type: 'number', formula: '=(MAX(C14:E14)-MIN(C14:E14))/MIN(C14:E14)' }, H14: { value: 'Supplier B' },
              A15: { value: 'GLASS-TUMBLER-SET' }, B15: { value: 'Handblown Glass Tumbler Set (4)' },
              C15: { value: 8.00, type: 'number' }, D15: { value: 9.20, type: 'number' }, E15: { value: 7.50, type: 'number' },
              F15: { value: 7.50, type: 'number', formula: '=MIN(C15:E15)' }, G15: { value: 0.227, type: 'number', formula: '=(MAX(C15:E15)-MIN(C15:E15))/MIN(C15:E15)' }, H15: { value: 'Supplier C' },
              ...quoteCells(16, [
                ['TOOL-HOSE-25FT', 'Expandable Garden Hose 25ft', 4.20, 3.85, 4.60, 'Supplier B'],
                ['KIT-COFFEE-MILL', 'Manual Coffee Grinder', 6.40, 7.10, 6.05, 'Supplier C'],
                ['HOME-RUG-2X3', 'Washable Entry Rug 2x3', 5.20, 4.70, 5.55, 'Supplier B'],
                ['LED-STRIP-5M', 'LED Strip Light 5m', 2.80, 3.10, 3.35, 'Supplier A'],
                ['PET-TOY-ROPE', 'Cotton Rope Pet Toy', 0.74, 0.86, 0.91, 'Supplier A'],
                ['DECOR-CANDLE-SET', 'Scented Candle Set (3)', 3.60, 4.05, 3.35, 'Supplier C'],
                ['AUTO-WIPER-22', '22-inch Hybrid Wiper Blade', 2.95, 3.45, 3.25, 'Supplier A'],
                ['PKG-TAPE-CLR', 'Clear Packing Tape 48mm', 0.52, 0.47, 0.60, 'Supplier B'],
                ['KITCHEN-SCALE-5KG', 'Digital Kitchen Scale 5kg', 4.80, 5.35, 5.05, 'Supplier A'],
                ['OUTDOOR-LANTERN', 'Rechargeable Camping Lantern', 8.90, 10.10, 9.70, 'Supplier A'],
                ['BEAUTY-BRUSH-SET', 'Makeup Brush Set (12)', 2.10, 2.45, 2.30, 'Supplier A'],
                ['FOOD-TEA-GIFT', 'Loose Leaf Tea Gift Tin', 3.05, 3.55, 3.30, 'Supplier A'],
                ['SHELF-BIN-SM', 'Small Storage Bin', 1.15, 1.02, 1.26, 'Supplier B'],
                ['CORK-COASTER-6', 'Cork Coaster Set (6)', 1.90, 2.25, 2.05, 'Supplier A'],
                ['LED-DRIVER-40W', '40W Constant Current LED Driver', 4.40, 5.20, 4.85, 'Supplier A'],
                ['PET-MAT-WASH', 'Washable Pet Feeding Mat', 1.65, 1.95, 1.82, 'Supplier A'],
                ['DECOR-GLASS-VASE', 'Glass Bud Vase Trio', 3.90, 4.65, 4.15, 'Supplier A'],
                ['AUTO-AIR-FILTER', 'Cabin Air Filter', 1.35, 1.62, 1.48, 'Supplier A'],
              ]),
            },
          },
          {
            properties: { sheetId: 2, title: 'Audit Trail', index: 2, gridProperties: { rowCount: 100, columnCount: 10 } },
            cells: {
              A1: { value: 'Date' }, B1: { value: 'User' }, C1: { value: 'Change' }, D1: { value: 'Old Value' }, E1: { value: 'New Value' },
              A2: { value: '2026-04-02' }, B2: { value: 'wei@' }, C2: { value: 'Rating update — Shenzhen Lumen' }, D2: { value: '4.0' }, E2: { value: '4.2' },
              A3: { value: '2026-04-05' }, B3: { value: 'ana@' }, C3: { value: 'Added supplier "São Paulo Têxtil"' }, D3: { value: '' }, E3: { value: 'New row' },
              A4: { value: '2026-04-10' }, B4: { value: 'mei@' }, C4: { value: 'Quote updated — TOOL-PRUNE-01 Supplier C' }, D4: { value: '3.15' }, E4: { value: '2.95' },
              A5: { value: '2026-04-12' }, B5: { value: 'jon@' }, C5: { value: 'Payment terms changed — Hangzhou Wellpack' }, D5: { value: 'Net 45' }, E5: { value: 'Net 30' },
              A6: { value: '2026-04-15' }, B6: { value: 'iris@' }, C6: { value: 'Note: "Breakage rate 4.2% — need corrective action"' }, D6: { value: '' }, E6: { value: 'Added to Ho Chi Minh Ceramics' },
              A7: { value: '2026-04-18' }, B7: { value: 'ravi@' }, C7: { value: 'MOQ reduced — Yiwu Meridian' }, D7: { value: '200' }, E7: { value: '100' },
              A8: { value: '2026-04-22' }, B8: { value: 'owen@' }, C8: { value: 'Cert added: UL — Foshan Northstar' }, D8: { value: 'ISO9001' }, E8: { value: 'ISO9001, UL' },
              A9: { value: '2026-05-01' }, B9: { value: 'sara@' }, C9: { value: 'Rating update — Guangzhou Orchid Beauty' }, D9: { value: '4.5' }, E9: { value: '4.8' },
              A10: { value: '2026-05-05' }, B10: { value: 'carlos@' }, C10: { value: 'Added supplier "Monterrey Steel"' }, D10: { value: '' }, E10: { value: 'New row' },
              A11: { value: '2026-05-10' }, B11: { value: 'anuj@' }, C11: { value: 'Lead time corrected — Rajkot Precision' }, D11: { value: '60' }, E11: { value: '55' },
              A12: { value: '2026-05-15' }, B12: { value: 'mei@' }, C12: { value: 'Quote added — GLASS-TUMBLER-SET all suppliers' }, D12: { value: '' }, E12: { value: '3 quotes entered' },
              ...tableCells(13, [
                ['2026-05-18', 'erin@', 'Added supplier "Pacific Northwest Tools"', '', 'New row'],
                ['2026-05-19', 'raka@', 'Lead time caution — Bandung Outdoor Supply', '41', '49'],
                ['2026-05-20', 'nora@', 'Added supplier "Toronto Pet Goods"', '', 'New row'],
                ['2026-05-21', 'kasia@', 'Quote added — PKG-TAPE-CLR Supplier B', '', '0.47'],
                ['2026-05-23', 'mei@', 'Pruning shears annual volume corrected', '3000', '2400'],
                ['2026-05-24', 'mai@', 'Ceramic rework option added — Da Nang Finishers', '', 'QC sign-off required'],
              ]),
            },
          },
        ],
      },

      // ── Cross-Border Inventory Tracker (4 sheets, ~75 rows) ──
      'sheet-inventory-004': {
        spreadsheetId: 'sheet-inventory-004',
        properties: { title: 'Cross-Border Inventory Tracker', locale: 'en_US', timeZone: 'America/New_York' },
        sheets: [
          {
            properties: { sheetId: 0, title: 'Warehouse Stock', index: 0, gridProperties: { rowCount: 300, columnCount: 26 } },
            cells: {
              A1: { value: 'SKU' }, B1: { value: 'Product Name' }, C1: { value: 'Warehouse' },
              D1: { value: 'On Hand' }, E1: { value: 'In Transit' }, F1: { value: 'Safety Stock' },
              G1: { value: 'Stockout Days' }, H1: { value: 'Last Replenish' }, I1: { value: 'Supplier' },
              J1: { value: 'Unit Cost (USD)' }, K1: { value: 'Total Value' }, L1: { value: 'Status' },
              // US-West warehouse
              A2: { value: 'LED-PANEL-60W' }, B2: { value: '60W LED Panel Light' }, C2: { value: 'US-West' },
              D2: { value: 420, type: 'number' }, E2: { value: 200, type: 'number' }, F2: { value: 100, type: 'number' },
              G2: { value: 0, type: 'number' }, H2: { value: '2026-05-20' }, I2: { value: 'Shenzhen Lumen' },
              J2: { value: 12.50, type: 'number' }, K2: { value: 5250, type: 'number', formula: '=D2*J2' }, L2: { value: 'In Stock' },
              A3: { value: 'PKG-KRAFT-M' }, B3: { value: 'Kraft Mailer Box (Medium)' }, C3: { value: 'US-West' },
              D3: { value: 8500, type: 'number' }, E3: { value: 0, type: 'number' }, F3: { value: 2000, type: 'number' },
              G3: { value: 0, type: 'number' }, H3: { value: '2026-05-15' }, I3: { value: 'Ningbo Harbor' },
              J3: { value: 0.38, type: 'number' }, K3: { value: 3230, type: 'number', formula: '=D3*J3' }, L3: { value: 'In Stock' },
              A4: { value: 'PET-BED-LG' }, B4: { value: 'Orthopedic Dog Bed (Large)' }, C4: { value: 'US-West' },
              D4: { value: 45, type: 'number' }, E4: { value: 150, type: 'number' }, F4: { value: 80, type: 'number' },
              G4: { value: 3, type: 'number' }, H4: { value: '2026-05-28' }, I4: { value: 'Dongguan Nova Pet' },
              J4: { value: 9.80, type: 'number' }, K4: { value: 441, type: 'number', formula: '=D4*J4' }, L4: { value: 'Low' },
              A5: { value: 'CAMP-TENT-2P' }, B5: { value: '2-Person Camping Tent' }, C5: { value: 'US-West' },
              D5: { value: 0, type: 'number' }, E5: { value: 300, type: 'number' }, F5: { value: 50, type: 'number' },
              G5: { value: 12, type: 'number' }, H5: { value: '2026-04-30' }, I5: { value: 'Xiamen Bluewave' },
              J5: { value: 22.00, type: 'number' }, K5: { value: 0, type: 'number', formula: '=D5*J5' }, L5: { value: 'Out' },
              A6: { value: 'BEAUTY-SERUM-VC' }, B6: { value: 'Vitamin C Serum 30ml' }, C6: { value: 'US-West' },
              D6: { value: 1200, type: 'number' }, E6: { value: 0, type: 'number' }, F6: { value: 500, type: 'number' },
              G6: { value: 0, type: 'number' }, H6: { value: '2026-05-22' }, I6: { value: 'Guangzhou Orchid Beauty' },
              J6: { value: 1.20, type: 'number' }, K6: { value: 1440, type: 'number', formula: '=D6*J6' }, L6: { value: 'In Stock' },
              // US-East warehouse
              A7: { value: 'LED-PANEL-60W' }, B7: { value: '60W LED Panel Light' }, C7: { value: 'US-East' },
              D7: { value: 180, type: 'number' }, E7: { value: 0, type: 'number' }, F7: { value: 100, type: 'number' },
              G7: { value: 0, type: 'number' }, H7: { value: '2026-05-10' }, I7: { value: 'Shenzhen Lumen' },
              J7: { value: 12.50, type: 'number' }, K7: { value: 2250, type: 'number', formula: '=D7*J7' }, L7: { value: 'In Stock' },
              A8: { value: 'KIT-KNIFE-5PC' }, B8: { value: '5-Piece Kitchen Knife Set' }, C8: { value: 'US-East' },
              D8: { value: 75, type: 'number' }, E8: { value: 100, type: 'number' }, F8: { value: 60, type: 'number' },
              G8: { value: 0, type: 'number' }, H8: { value: '2026-05-25' }, I8: { value: 'Istanbul Metalworks' },
              J8: { value: 16.50, type: 'number' }, K8: { value: 1237.50, type: 'number', formula: '=D8*J8' }, L8: { value: 'In Stock' },
              A9: { value: 'PET-BED-LG' }, B9: { value: 'Orthopedic Dog Bed (Large)' }, C9: { value: 'US-East' },
              D9: { value: 22, type: 'number' }, E9: { value: 0, type: 'number' }, F9: { value: 80, type: 'number' },
              G9: { value: 5, type: 'number' }, H9: { value: '2026-05-18' }, I9: { value: 'Dongguan Nova Pet' },
              J9: { value: 9.80, type: 'number' }, K9: { value: 215.60, type: 'number', formula: '=D9*J9' }, L9: { value: 'Critical' },
              A10: { value: 'BEAUTY-SERUM-VC' }, B10: { value: 'Vitamin C Serum 30ml' }, C10: { value: 'US-East' },
              D10: { value: 800, type: 'number' }, E10: { value: 500, type: 'number' }, F10: { value: 500, type: 'number' },
              G10: { value: 0, type: 'number' }, H10: { value: '2026-05-20' }, I10: { value: 'Guangzhou Orchid Beauty' },
              J10: { value: 1.20, type: 'number' }, K10: { value: 960, type: 'number', formula: '=D10*J10' }, L10: { value: 'In Stock' },
              // EU-DE warehouse
              A11: { value: 'LED-PANEL-60W' }, B11: { value: '60W LED Panel Light' }, C11: { value: 'EU-DE' },
              D11: { value: 95, type: 'number' }, E11: { value: 400, type: 'number' }, F11: { value: 150, type: 'number' },
              G11: { value: 2, type: 'number' }, H11: { value: '2026-05-05' }, I11: { value: 'Foshan Northstar' },
              J11: { value: 13.80, type: 'number' }, K11: { value: 1311, type: 'number', formula: '=D11*J11' }, L11: { value: 'Low' },
              A12: { value: 'TOOL-PRUNE-01' }, B12: { value: 'Bypass Pruning Shears' }, C12: { value: 'EU-DE' },
              D12: { value: 310, type: 'number' }, E12: { value: 0, type: 'number' }, F12: { value: 100, type: 'number' },
              G12: { value: 0, type: 'number' }, H12: { value: '2026-05-12' }, I12: { value: 'Qingdao Greenfield' },
              J12: { value: 2.95, type: 'number' }, K12: { value: 914.50, type: 'number', formula: '=D12*J12' }, L12: { value: 'In Stock' },
              A13: { value: 'DECOR-VASE-CER' }, B13: { value: 'Ceramic Flower Vase, 12"' }, C13: { value: 'EU-DE' },
              D13: { value: 0, type: 'number' }, E13: { value: 0, type: 'number' }, F13: { value: 40, type: 'number' },
              G13: { value: 18, type: 'number' }, H13: { value: '2026-04-15' }, I13: { value: 'Ho Chi Minh Ceramics' },
              J13: { value: 4.30, type: 'number' }, K13: { value: 0, type: 'number', formula: '=D13*J13' }, L13: { value: 'Out' },
              // APAC-SG warehouse
              A14: { value: 'BEAUTY-SERUM-VC' }, B14: { value: 'Vitamin C Serum 30ml' }, C14: { value: 'APAC-SG' },
              D14: { value: 2500, type: 'number' }, E14: { value: 1000, type: 'number' }, F14: { value: 800, type: 'number' },
              G14: { value: 0, type: 'number' }, H14: { value: '2026-05-28' }, I14: { value: 'Guangzhou Orchid Beauty' },
              J14: { value: 1.20, type: 'number' }, K14: { value: 3000, type: 'number', formula: '=D14*J14' }, L14: { value: 'In Stock' },
              A15: { value: 'SPICE-TURM-ORG' }, B15: { value: 'Organic Turmeric Powder 500g' }, C15: { value: 'APAC-SG' },
              D15: { value: 180, type: 'number' }, E15: { value: 0, type: 'number' }, F15: { value: 100, type: 'number' },
              G15: { value: 0, type: 'number' }, H15: { value: '2026-05-15' }, I15: { value: 'Chennai Spice Exports' },
              J15: { value: 3.40, type: 'number' }, K15: { value: 612, type: 'number', formula: '=D15*J15' }, L15: { value: 'In Stock' },
              A16: { value: 'CAMP-TENT-2P' }, B16: { value: '2-Person Camping Tent' }, C16: { value: 'APAC-SG' },
              D16: { value: 15, type: 'number' }, E16: { value: 80, type: 'number' }, F16: { value: 30, type: 'number' },
              G16: { value: 0, type: 'number' }, H16: { value: '2026-05-22' }, I16: { value: 'Xiamen Bluewave' },
              J16: { value: 22.00, type: 'number' }, K16: { value: 330, type: 'number', formula: '=D16*J16' }, L16: { value: 'Low' },
              ...inventoryCells(17, [
                ['PKG-BUBBLE-LG', 'Bubble Wrap Roll (Large)', 'US-West', 3200, 1000, 1200, 0, '2026-05-29', 'Ningbo Harbor', 1.65, 'In Stock'],
                ['AUTO-FILTER-OIL', 'Oil Filter (Universal)', 'US-West', 600, 0, 300, 0, '2026-05-16', 'Rajkot Precision Parts', 0.88, 'In Stock'],
                ['STEEL-SHELF-3T', '3-Tier Steel Storage Shelf', 'US-West', 70, 200, 90, 0, '2026-05-11', 'Monterrey Steel', 12.80, 'Low'],
                ['GLASS-TUMBLER-SET', 'Handblown Glass Tumbler Set (4)', 'US-West', 260, 0, 120, 0, '2026-05-19', 'Izmir Glass', 7.50, 'In Stock'],
                ['LEATHER-WALLET', 'Genuine Leather Bifold Wallet', 'US-West', 180, 100, 150, 0, '2026-05-21', 'Dhaka Leather Works', 4.80, 'In Stock'],
                ['SPICE-TURM-ORG', 'Organic Turmeric Powder 500g', 'US-West', 95, 200, 120, 0, '2026-05-24', 'Chennai Spice Exports', 3.40, 'Low'],
                ['TOOL-HOSE-25FT', 'Expandable Garden Hose 25ft', 'US-East', 410, 0, 180, 0, '2026-05-27', 'Pacific Northwest Tools', 3.85, 'In Stock'],
                ['KIT-COFFEE-MILL', 'Manual Coffee Grinder', 'US-East', 130, 80, 120, 0, '2026-05-17', 'Suzhou BrightHome', 6.05, 'In Stock'],
                ['HOME-RUG-2X3', 'Washable Entry Rug 2x3', 'US-East', 260, 0, 140, 0, '2026-05-18', 'São Paulo Têxtil', 4.70, 'In Stock'],
                ['LED-STRIP-5M', 'LED Strip Light 5m', 'US-East', 380, 300, 220, 0, '2026-05-25', 'Rayong LED Components', 2.80, 'In Stock'],
                ['PET-TOY-ROPE', 'Cotton Rope Pet Toy', 'US-East', 1200, 0, 600, 0, '2026-05-26', 'Penang Pet Comfort', 0.74, 'In Stock'],
                ['DECOR-CANDLE-SET', 'Scented Candle Set (3)', 'US-East', 185, 0, 160, 0, '2026-05-22', 'Porto Cork & Home', 3.35, 'In Stock'],
                ['AUTO-WIPER-22', '22-inch Hybrid Wiper Blade', 'EU-DE', 240, 200, 220, 0, '2026-05-13', 'Krakow Auto Filters', 2.95, 'In Stock'],
                ['PKG-TAPE-CLR', 'Clear Packing Tape 48mm', 'EU-DE', 5200, 0, 3000, 0, '2026-05-14', 'Poznan Packaging', 0.47, 'In Stock'],
                ['KITCHEN-SCALE-5KG', 'Digital Kitchen Scale 5kg', 'EU-DE', 210, 0, 160, 0, '2026-05-12', 'Busan Alloy Works', 4.80, 'In Stock'],
                ['OUTDOOR-LANTERN', 'Rechargeable Camping Lantern', 'EU-DE', 88, 240, 110, 0, '2026-05-08', 'Bandung Outdoor Supply', 8.90, 'Low'],
                ['BEAUTY-BRUSH-SET', 'Makeup Brush Set (12)', 'EU-DE', 900, 600, 700, 0, '2026-05-23', 'Bangkok Wellness Labs', 2.10, 'In Stock'],
                ['FOOD-TEA-GIFT', 'Loose Leaf Tea Gift Tin', 'EU-DE', 140, 0, 100, 0, '2026-05-20', 'Chennai Spice Exports', 3.05, 'In Stock'],
                ['SHELF-BIN-SM', 'Small Storage Bin', 'APAC-SG', 1500, 0, 800, 0, '2026-05-28', 'Yiwu Meridian', 1.02, 'In Stock'],
                ['CORK-COASTER-6', 'Cork Coaster Set (6)', 'APAC-SG', 360, 0, 220, 0, '2026-05-18', 'Porto Cork & Home', 1.90, 'In Stock'],
                ['LED-DRIVER-40W', '40W Constant Current LED Driver', 'APAC-SG', 115, 250, 150, 0, '2026-05-17', 'Foshan Northstar', 4.40, 'Low'],
                ['PET-MAT-WASH', 'Washable Pet Feeding Mat', 'APAC-SG', 680, 0, 350, 0, '2026-05-26', 'Toronto Pet Goods', 1.65, 'In Stock'],
                ['DECOR-GLASS-VASE', 'Glass Bud Vase Trio', 'APAC-SG', 220, 120, 180, 0, '2026-05-19', 'Valencia Glass Studio', 3.90, 'In Stock'],
                ['AUTO-AIR-FILTER', 'Cabin Air Filter', 'APAC-SG', 340, 0, 260, 0, '2026-05-21', 'Krakow Auto Filters', 1.35, 'In Stock'],
              ]),
            },
          },
          {
            properties: { sheetId: 1, title: 'Reorder Queue', index: 1, gridProperties: { rowCount: 100, columnCount: 10 } },
            cells: {
              A1: { value: 'SKU' }, B1: { value: 'Qty Needed' }, C1: { value: 'Target Warehouse' },
              D1: { value: 'ETA' }, E1: { value: 'PO #' }, F1: { value: 'Notes' },
              A2: { value: 'CAMP-TENT-2P' }, B2: { value: 300, type: 'number' }, C2: { value: 'US-West' },
              D2: { value: '2026-06-15' }, E2: { value: 'PO-2026-0412' }, F2: { value: 'Urgent — 12 days stockout' },
              A3: { value: 'PET-BED-LG' }, B3: { value: 200, type: 'number' }, C3: { value: 'US-East' },
              D3: { value: '2026-06-10' }, E3: { value: 'PO-2026-0415' }, F3: { value: 'Split shipment: 100 sea + 100 air' },
              A4: { value: 'DECOR-VASE-CER' }, B4: { value: 150, type: 'number' }, C4: { value: 'EU-DE' },
              D4: { value: '2026-06-20' }, E4: { value: 'PO-2026-0418' }, F4: { value: '18 days out; supplier confirmed capacity' },
              A5: { value: 'PET-BED-LG' }, B5: { value: 150, type: 'number' }, C5: { value: 'US-West' },
              D5: { value: '2026-06-12' }, E5: { value: 'PO-2026-0415' }, F5: { value: 'Same PO as US-East; split at port' },
              A6: { value: 'LED-PANEL-60W' }, B6: { value: 500, type: 'number' }, C6: { value: 'EU-DE' },
              D6: { value: '2026-06-18' }, E6: { value: 'PO-2026-0420' }, F6: { value: 'Switching from Lumen to Northstar for EU' },
              A7: { value: 'CAMP-TENT-2P' }, B7: { value: 80, type: 'number' }, C7: { value: 'APAC-SG' },
              D7: { value: '2026-06-08' }, E7: { value: 'PO-2026-0422' }, F7: { value: 'Small top-up; monsoon season demand' },
              A8: { value: 'BEAUTY-SERUM-VC' }, B8: { value: 2000, type: 'number' }, C8: { value: 'US-East' },
              D8: { value: '2026-06-25' }, E8: { value: 'PO-2026-0425' }, F8: { value: 'Q3 promo build-up; Orchid Beauty confirmed' },
              ...tableCells(9, [
                ['STEEL-SHELF-3T', 200, 'US-West', '2026-06-22', 'PO-2026-0426', 'Inbound covers safety stock; watch only'],
                ['SPICE-TURM-ORG', 200, 'US-West', '2026-06-11', 'PO-2026-0427', 'Short on hand but covered by booked air pallet'],
                ['OUTDOOR-LANTERN', 240, 'EU-DE', '2026-06-19', 'PO-2026-0428', 'Seasonal display build; supplier sample delay'],
                ['LED-DRIVER-40W', 250, 'APAC-SG', '2026-06-14', 'PO-2026-0429', 'Pairs with LED-PANEL-60W promotion'],
                ['AUTO-WIPER-22', 200, 'EU-DE', '2026-06-17', 'PO-2026-0430', 'Covered after in-transit, no escalation unless customs slip'],
                ['DECOR-GLASS-VASE', 120, 'APAC-SG', '2026-06-16', 'PO-2026-0431', 'Fragile-packaging trial; monitor breakage reports'],
                ['PET-MAT-WASH', 400, 'US-East', '2026-06-21', 'PO-2026-0432', 'Promo buffer only'],
                ['PKG-TAPE-CLR', 3000, 'EU-DE', '2026-06-09', 'PO-2026-0433', 'Fast replenishment; no standup escalation'],
              ]),
            },
          },
          {
            properties: { sheetId: 2, title: 'Cost Summary', index: 2, gridProperties: { rowCount: 50, columnCount: 10 } },
            cells: {
              A1: { value: 'Warehouse' }, B1: { value: 'SKU Count' }, C1: { value: 'Total Inventory Value (USD)' },
              D1: { value: 'Avg Unit Cost' }, E1: { value: 'Items at Risk' },
              A2: { value: 'US-West' }, B2: { value: 11, type: 'number' }, C2: { value: 20202, type: 'number' },
              D2: { value: 6.99, type: 'number' }, E2: { value: 4, type: 'number' },
              A3: { value: 'US-East' }, B3: { value: 10, type: 'number' }, C3: { value: 10821.85, type: 'number' },
              D3: { value: 6.15, type: 'number' }, E3: { value: 1, type: 'number' },
              A4: { value: 'EU-DE' }, B4: { value: 9, type: 'number' }, C4: { value: 9485.70, type: 'number' },
              D4: { value: 4.81, type: 'number' }, E4: { value: 3, type: 'number' },
              A5: { value: 'APAC-SG' }, B5: { value: 9, type: 'number' }, C5: { value: 9101, type: 'number' },
              D5: { value: 4.54, type: 'number' }, E5: { value: 2, type: 'number' },
              A6: { value: 'Grand Total', bold: true }, B6: { value: 39, type: 'number', formula: '=SUM(B2:B5)' },
              C6: { value: 49610.55, type: 'number', formula: '=SUM(C2:C5)' },
              D6: { value: 5.71, type: 'number' }, E6: { value: 10, type: 'number', formula: '=SUM(E2:E5)' },
            },
          },
          {
            properties: { sheetId: 3, title: 'PO Ledger', index: 3, gridProperties: { rowCount: 120, columnCount: 12 } },
            cells: {
              A1: { value: 'PO #' }, B1: { value: 'SKU' }, C1: { value: 'Target Warehouse' },
              D1: { value: 'Qty' }, E1: { value: 'Transport Mode' }, F1: { value: 'ETA' },
              G1: { value: 'Status' }, H1: { value: 'Expedite Eligible' }, I1: { value: 'Hold / Watch Reason' },
              J1: { value: 'Owner' }, K1: { value: 'Supplier' }, L1: { value: 'Last Carrier Update' },
              ...tableCells(2, [
                ['PO-2026-0412', 'CAMP-TENT-2P', 'US-West', 300, 'Ocean expedited', '2026-06-15', 'Departed XMN', 'Yes', 'Second-source quote still unapproved', 'lee@', 'Xiamen Bluewave', '2026-06-02'],
                ['PO-2026-0415', 'PET-BED-LG', 'US-East', 200, '100 air + 100 sea', '2026-06-10', 'Air split booked', 'Yes', 'Protect air split; sea leg alone misses safety stock', 'owen@', 'Dongguan Nova Pet', '2026-06-01'],
                ['PO-2026-0418', 'DECOR-VASE-CER', 'EU-DE', 150, 'Ocean', '2026-06-20', 'QC hold', 'Yes', 'Packaging CAPA required after 4.2% breakage', 'tran@', 'Ho Chi Minh Ceramics', '2026-06-03'],
                ['PO-2026-0420', 'LED-PANEL-60W', 'EU-DE', 500, 'Ocean', '2026-06-18', 'On water', 'No', 'In-transit quantity covers safety stock', 'yuki@', 'Foshan Northstar', '2026-06-01'],
                ['PO-2026-0422', 'CAMP-TENT-2P', 'APAC-SG', 80, 'Truck + feeder', '2026-06-08', 'Booked', 'No', 'APAC net after in-transit is positive', 'lee@', 'Xiamen Bluewave', '2026-06-02'],
                ['PO-2026-0426', 'STEEL-SHELF-3T', 'US-West', 200, 'Rail', '2026-06-22', 'Booked', 'No', 'Low on hand but inbound covers buffer', 'carlos@', 'Monterrey Steel', '2026-06-02'],
                ['PO-2026-0427', 'SPICE-TURM-ORG', 'US-West', 200, 'Air pallet', '2026-06-11', 'Customs pre-clear', 'No', 'Shortfall covered by booked air pallet', 'priya@', 'Chennai Spice Exports', '2026-06-01'],
                ['PO-2026-0428', 'OUTDOOR-LANTERN', 'EU-DE', 240, 'Ocean', '2026-06-19', 'Supplier sample delay', 'Watch', 'Display build only; no current stockout', 'raka@', 'Bandung Outdoor Supply', '2026-05-31'],
                ['PO-2026-0429', 'LED-DRIVER-40W', 'APAC-SG', 250, 'Ocean', '2026-06-14', 'On water', 'No', 'Pairs with LED panel promo; net positive', 'somchai@', 'Rayong LED Components', '2026-06-02'],
                ['PO-2026-0430', 'AUTO-WIPER-22', 'EU-DE', 200, 'Ocean', '2026-06-17', 'At origin port', 'No', 'Covered after in-transit', 'marek@', 'Krakow Auto Filters', '2026-06-01'],
                ['PO-2026-0431', 'DECOR-GLASS-VASE', 'APAC-SG', 120, 'Ocean', '2026-06-16', 'Fragile-pack trial', 'Watch', 'Monitor breakage only', 'lucia@', 'Valencia Glass Studio', '2026-05-30'],
                ['PO-2026-0433', 'PKG-TAPE-CLR', 'EU-DE', 3000, 'Air', '2026-06-09', 'Booked', 'No', 'Routine replenishment', 'kasia@', 'Poznan Packaging', '2026-06-02'],
              ]),
            },
          },
        ],
      },
    },
    presentations: {
      'pres-launch-101': {
        presentationId: 'pres-launch-101',
        title: 'AcmeCloud Launch Plan',
        pageSize: { width: { magnitude: 9144000, unit: 'EMU' }, height: { magnitude: 5143500, unit: 'EMU' } },
        slides: [
          {
            objectId: 'g_slide_001',
            layout: 'TITLE',
            background: '#0b57d0',
            pageElements: [
              {
                objectId: 'el_001_title', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [{ runs: [{ content: 'AcmeCloud Launch Plan' }] }] } },
                transform: { x: 80, y: 140, width: 800, height: 70 },
                style: { fontSize: 44, color: '#ffffff', fontWeight: 700, align: 'center' },
              },
              {
                objectId: 'el_001_sub', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [{ runs: [{ content: 'GA on April 14 · Prepared by the AcmeCloud team' }] }] } },
                transform: { x: 80, y: 240, width: 800, height: 36 },
                style: { fontSize: 18, color: '#dbe6ff', align: 'center' },
              },
            ],
          },
          {
            objectId: 'g_slide_002', layout: 'TITLE_AND_BODY', background: '#ffffff',
            pageElements: [
              {
                objectId: 'el_002_title', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [{ runs: [{ content: 'Why now' }] }] } },
                transform: { x: 60, y: 50, width: 820, height: 60 },
                style: { fontSize: 32, color: '#1f2937', fontWeight: 700 },
              },
              {
                objectId: 'el_002_body', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [
                  { runs: [{ content: '· Pipeline grew 38% over the last two quarters' }] },
                  { runs: [{ content: '· Top 5 enterprise prospects are blocked on the new SSO flow' }] },
                  { runs: [{ content: '· Competitor parity gap closes once billing migration ships' }] },
                ] } },
                transform: { x: 60, y: 130, width: 820, height: 280 },
                style: { fontSize: 20, color: '#1f2937', lineHeight: 1.6 },
              },
            ],
          },
          {
            objectId: 'g_slide_003', layout: 'TITLE_AND_BODY', background: '#ffffff',
            pageElements: [
              {
                objectId: 'el_003_title', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [{ runs: [{ content: 'Launch milestones' }] }] } },
                transform: { x: 60, y: 50, width: 820, height: 60 },
                style: { fontSize: 32, color: '#1f2937', fontWeight: 700 },
              },
              {
                objectId: 'el_003_table', type: 'table',
                table: {
                  rows: 4, columns: 3,
                  tableRows: [
                    { tableCells: [{ text: 'Milestone' }, { text: 'Owner' }, { text: 'Target' }] },
                    { tableCells: [{ text: 'Beta cohort lock' }, { text: 'Maya' }, { text: 'Mar 18' }] },
                    { tableCells: [{ text: 'Pricing finalized' }, { text: 'Andre' }, { text: 'Mar 25' }] },
                    { tableCells: [{ text: 'GA launch' }, { text: 'Priya' }, { text: 'Apr 14' }] },
                  ],
                },
                transform: { x: 60, y: 130, width: 820, height: 280 },
              },
            ],
          },
          {
            objectId: 'g_slide_004', layout: 'TITLE_AND_BODY', background: '#0b57d0',
            pageElements: [
              {
                objectId: 'el_004_title', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [{ runs: [{ content: 'Next checkpoint' }] }] } },
                transform: { x: 60, y: 110, width: 820, height: 60 },
                style: { fontSize: 36, color: '#ffffff', fontWeight: 700, align: 'center' },
              },
              {
                objectId: 'el_004_body', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [{ runs: [{ content: 'Friday standup · Review marketing brief and pricing one-pager' }] }] } },
                transform: { x: 60, y: 200, width: 820, height: 40 },
                style: { fontSize: 20, color: '#dbe6ff', align: 'center' },
              },
            ],
          },
        ],
      },
      'pres-allhands-202': {
        presentationId: 'pres-allhands-202',
        title: 'March All-Hands',
        pageSize: { width: { magnitude: 9144000, unit: 'EMU' }, height: { magnitude: 5143500, unit: 'EMU' } },
        slides: [
          {
            objectId: 'g_ah_001', layout: 'TITLE', background: '#111827',
            pageElements: [{
              objectId: 'el_ah_001_title', type: 'shape',
              shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [{ runs: [{ content: 'March All-Hands' }] }] } },
              transform: { x: 80, y: 160, width: 800, height: 70 },
              style: { fontSize: 44, color: '#ffffff', fontWeight: 700, align: 'center' },
            }],
          },
          {
            objectId: 'g_ah_002', layout: 'TITLE_AND_BODY', background: '#ffffff',
            pageElements: [
              {
                objectId: 'el_ah_002_title', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [{ runs: [{ content: 'Quarter highlights' }] }] } },
                transform: { x: 60, y: 50, width: 820, height: 60 },
                style: { fontSize: 32, color: '#1f2937', fontWeight: 700 },
              },
              {
                objectId: 'el_ah_002_body', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [
                  { runs: [{ content: '· Revenue +18% QoQ' }] },
                  { runs: [{ content: '· Two new enterprise logos signed' }] },
                  { runs: [{ content: '· Mobile retention up 9 points' }] },
                ] } },
                transform: { x: 60, y: 130, width: 820, height: 280 },
                style: { fontSize: 22, color: '#1f2937', lineHeight: 1.6 },
              },
            ],
          },
        ],
      },

      // ── Q2 Sourcing Review (6 slides) ──
      'pres-sourcing-review-303': {
        presentationId: 'pres-sourcing-review-303',
        title: 'Q2 Sourcing Review — Supply Chain Ops',
        pageSize: { width: { magnitude: 9144000, unit: 'EMU' }, height: { magnitude: 5143500, unit: 'EMU' } },
        slides: [
          {
            objectId: 'g_sr_001', layout: 'TITLE', background: '#1a3a5c',
            pageElements: [
              { objectId: 'el_sr_001_title', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [{ runs: [{ content: 'Q2 Sourcing Review' }] }] } },
                transform: { x: 80, y: 130, width: 800, height: 70 },
                style: { fontSize: 44, color: '#ffffff', fontWeight: 700, align: 'center' } },
              { objectId: 'el_sr_001_sub', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [{ runs: [{ content: 'Supply Chain Ops · June 2026' }] }] } },
                transform: { x: 80, y: 220, width: 800, height: 36 },
                style: { fontSize: 20, color: '#a3c4e8', align: 'center' } },
            ],
          },
          {
            objectId: 'g_sr_002', layout: 'TITLE_AND_BODY', background: '#ffffff',
            pageElements: [
              { objectId: 'el_sr_002_title', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [{ runs: [{ content: 'Key Metrics' }] }] } },
                transform: { x: 60, y: 50, width: 820, height: 60 },
                style: { fontSize: 32, color: '#1f2937', fontWeight: 700 } },
              { objectId: 'el_sr_002_body', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [
                  { runs: [{ content: '· Active suppliers: 19 across 7 countries' }] },
                  { runs: [{ content: '· Average lead time: 36 days (down from 42 in Q1)' }] },
                  { runs: [{ content: '· Quote spread: 9.1% – 30.5% across SKUs' }] },
                  { runs: [{ content: '· Inventory coverage: 82% of SKUs above safety stock' }] },
                  { runs: [{ content: '· Total inventory value: $21,192 across 4 warehouses' }] },
                ] } },
                transform: { x: 60, y: 130, width: 820, height: 280 },
                style: { fontSize: 20, color: '#1f2937', lineHeight: 1.6 } },
            ],
          },
          {
            objectId: 'g_sr_003', layout: 'TITLE_AND_BODY', background: '#ffffff',
            pageElements: [
              { objectId: 'el_sr_003_title', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [{ runs: [{ content: 'Supplier Performance — Top 5' }] }] } },
                transform: { x: 60, y: 50, width: 820, height: 60 },
                style: { fontSize: 32, color: '#1f2937', fontWeight: 700 } },
              { objectId: 'el_sr_003_table', type: 'table',
                table: {
                  rows: 6, columns: 5,
                  tableRows: [
                    { tableCells: [{ text: 'Supplier' }, { text: 'Rating' }, { text: 'On-Time %' }, { text: 'Defect Rate' }, { text: 'Trend' }] },
                    { tableCells: [{ text: '广州兰花美容 (Orchid Beauty)' }, { text: '4.8' }, { text: '98%' }, { text: '0.3%' }, { text: '↑' }] },
                    { tableCells: [{ text: '苏州明居 (BrightHome)' }, { text: '4.7' }, { text: '96%' }, { text: '0.5%' }, { text: '→' }] },
                    { tableCells: [{ text: '厦门蓝波 (Bluewave Outdoor)' }, { text: '4.6' }, { text: '94%' }, { text: '0.8%' }, { text: '↑' }] },
                    { tableCells: [{ text: '青岛绿野 (Greenfield Tools)' }, { text: '4.5' }, { text: '95%' }, { text: '0.4%' }, { text: '→' }] },
                    { tableCells: [{ text: '佛山北极星 (Northstar)' }, { text: '4.4' }, { text: '92%' }, { text: '1.1%' }, { text: '↓' }] },
                  ],
                },
                transform: { x: 60, y: 130, width: 820, height: 280 } },
            ],
          },
          {
            objectId: 'g_sr_004', layout: 'TITLE_AND_BODY', background: '#ffffff',
            pageElements: [
              { objectId: 'el_sr_004_title', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [{ runs: [{ content: 'Risk Assessment' }] }] } },
                transform: { x: 60, y: 50, width: 820, height: 60 },
                style: { fontSize: 32, color: '#1f2937', fontWeight: 700 } },
              { objectId: 'el_sr_004_body', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [
                  { runs: [{ content: 'HIGH — CAMP-TENT-2P: 12-day stockout at US-West; single-source (Xiamen Bluewave)' }] },
                  { runs: [{ content: 'HIGH — DECOR-VASE-CER: 18-day stockout at EU-DE; breakage rate 4.2% (Ho Chi Minh Ceramics)' }] },
                  { runs: [{ content: 'MEDIUM — PET-BED-LG: US-East below safety stock; split shipment in transit' }] },
                  { runs: [{ content: 'MEDIUM — São Paulo Têxtil: quality inconsistency on dye lots; corrective action pending' }] },
                  { runs: [{ content: 'LOW — LED-PANEL-60W at EU-DE: temporarily low but 400 units in transit' }] },
                ] } },
                transform: { x: 60, y: 130, width: 820, height: 280 },
                style: { fontSize: 18, color: '#1f2937', lineHeight: 1.8 } },
            ],
          },
          {
            objectId: 'g_sr_005', layout: 'TITLE_AND_BODY', background: '#ffffff',
            pageElements: [
              { objectId: 'el_sr_005_title', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [{ runs: [{ content: 'Cost Optimization Wins' }] }] } },
                transform: { x: 60, y: 50, width: 820, height: 60 },
                style: { fontSize: 32, color: '#1f2937', fontWeight: 700 } },
              { objectId: 'el_sr_005_body', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [
                  { runs: [{ content: '· Pruning shears: renegotiated with Supplier C → saved $0.25/unit ($3.20→$2.95), ~$750/yr on 3k units' }] },
                  { runs: [{ content: '· Packaging: switched Kraft mailer to Ningbo Harbor → $0.04/box savings at 20k/mo = $9,600/yr' }] },
                  { runs: [{ content: '· Nearshoring pilot: Monterrey Steel for 3-tier shelves landed cost 8% under CN after tariff' }] },
                  { runs: [{ content: '· Payment terms: Hangzhou Wellpack moved from Net 45 → Net 30 in exchange for volume commitment' }] },
                ] } },
                transform: { x: 60, y: 130, width: 820, height: 280 },
                style: { fontSize: 18, color: '#1f2937', lineHeight: 1.8 } },
            ],
          },
          {
            objectId: 'g_sr_006', layout: 'TITLE_AND_BODY', background: '#1a3a5c',
            pageElements: [
              { objectId: 'el_sr_006_title', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [{ runs: [{ content: 'Next Steps' }] }] } },
                transform: { x: 60, y: 80, width: 820, height: 60 },
                style: { fontSize: 36, color: '#ffffff', fontWeight: 700, align: 'center' } },
              { objectId: 'el_sr_006_body', type: 'shape',
                shape: { shapeType: 'TEXT_BOX', text: { paragraphs: [
                  { runs: [{ content: '1. Qualify second source for camping tents (target: July)' }] },
                  { runs: [{ content: '2. Corrective action review for Ho Chi Minh Ceramics breakage' }] },
                  { runs: [{ content: '3. São Paulo Têxtil dye lot audit — send QC team on-site' }] },
                  { runs: [{ content: '4. Expand Monterrey Steel pilot to 2 more SKUs' }] },
                  { runs: [{ content: '5. Q3 safety stock recalculation for monsoon season (APAC-SG)' }] },
                ] } },
                transform: { x: 60, y: 160, width: 820, height: 300 },
                style: { fontSize: 20, color: '#a3c4e8', lineHeight: 1.8 } },
            ],
          },
        ],
      },
    },
  };
}
